apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sovannlyna-html-v34-certificate
  namespace: sovannlyna-html-v34
spec:
  secretName: sovannlyna-html-v34-secret-tls
  commonName: sovannlyna-html-v34.assessify.org
  dnsNames:
  - sovannlyna-html-v34.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
